### ISSUE TITLE
[STORY] Organization Groups

### ISSUE THREAD

**Issue by juarezasjunior** [juarezasjunior/KomberNet#10]
**Description**
Create pages to search and to add/edit organization groups. Also, create a way to invite users to join in that organization group. An user can see only organization groups that he is related and he must edit only if he is administrator of the organization group.

---
**Screenshots / Mockups**
NA.

---
**Acceptance Criteria**
- [ ] Page to search my organization groups
- [ ] Page to add/edit an organization group
- [ ] Page to manage users related with that organization group
- [ ] A related user should accept to belongs to that organization group
- [ ] The pages to add/edit organization groups and their related users are available only to administrators of that organization group

---
**Notes**
NA.

---
**Tasks**
NA.
