### ISSUE TITLE
[STORY] My Organization Group Component

### ISSUE THREAD

**Issue by juarezasjunior** [juarezasjunior/KomberNet#11]
**Description**
Create a component to search all organization groups that the current user is related. When selecting an organization group, his option should be storaged locally in order that when opening another page having this component, the last option should be filled automatically. Also, add this component to the search component. It should appear before the search string field. The search component should have a parameter to show this Organization Group component. The parameter could be called organization context and have three options: none, organization group and branch/office. The branch/office option will be implemented later.

---
**Screenshots / Mockups**
NA.

---
**Acceptance Criteria**
- [ ] New DropDownDataGrid My Organization Groups Component
- [ ] Should list only organization groups that the current user is related (as administrator or not)
- [ ] Add this component to the Search component, before the search string field
- [ ] Add an option to show this new DropDownDataGrid in Search component or not, according with the OrganizationContext.

---
**Notes**
NA.

---
**Tasks**
NA.
