### ISSUE TITLE
[STORY] Branches/Offices

### ISSUE THREAD

**Issue by juarezasjunior** [juarezasjunior/KomberNet#13]
**Description**
Create pages to search and add/edit branches/offices. The current user can only add/edit branches/offices to organization groups that he is administrator. Otherwise, he can only see the branches/offices from organization groups that he is related but not administrator.

A branch/office has these fields: organization subgroup and name.

---
**Screenshots / Mockups**
NA.

---
**Acceptance Criteria**
- [ ] Page to search Branch/Offices (OrganizationContext: Organization Group)
- [ ] Page to add/edit Branches/Offices
- [ ] The current user can add/edit only branches/offices from organization gruops that he is administrator.

---
**Notes**
NA.

---
**Tasks**
NA.
