### ISSUE TITLE
[STORY] Users of Organization Groups

### ISSUE THREAD

**Issue by juarezasjunior** [juarezasjunior/KomberNet#16]
**Description**
Create pages to search and add/edit users of an organization group. Also, create a way to invite users to join in that organization group. An organization group must have at least one administrator user. If the current user is not an administrator of the organization group, he cannot add/edit/delete users of that group.

---
**Screenshots / Mockups**
NA.

---
**Acceptance Criteria**
- [ ] Page to search and add/edit users of an organization group
- [ ] A related user should accept to belongs to that organization group
- [ ] An organization group must have at least one administrator user

---
**Notes**
NA.

---
**Tasks**
NA.
