### ISSUE TITLE
[STORY] Permissions

### ISSUE THREAD

**Issue by juarezasjunior** [juarezasjunior/KomberNet#19]
**Description**
Create pages to search and add/edit permissions. If the current user is not an administrator of the organization group, he cannot add/edit permissions.
A permission of a feature can be added to a user or a permission group. Also, the context of a feature is a, organization group or a branch/office. So, features related with branch/office, you should select the branches/offices of that organization group.

---
**Screenshots / Mockups**
NA.

---
**Acceptance Criteria**
- [ ] Page to search and add/edit permissions
- [ ] Add a simple way to select the features that the user has access
- [ ] If a feature is granted to branch/office context, you must select the branches/offices that the user has permission 
- [ ] The current user can add/edit only permissions from organization groups that he is administrator

---
**Notes**
NA.

---
**Tasks**
NA.
