### ISSUE TITLE
[STORY] Send email to confirm new user

### ISSUE THREAD

**Issue by juarezasjunior** [juarezasjunior/KomberNet#6]
**Description**
When creating an user, his email address should be confirmed. To do that, he is going to receive an email with a confirmation link. He shouldn't be ready to use the system without this confirmation. When confirming, he should be redirected to a page saying thank you for the confirmation.

---
**Screenshots / Mockups**
NA.

---
**Acceptance Criteria**
- [ ] New user should receive a confirmation email with a link to confirm
- [ ] This new user cannot use the system without confirm
- [ ] After confirming, a page saying thank you should be displayed.

---
**Notes**
NA.

---
**Tasks**
NA
