### ISSUE TITLE
[STORY] Reset password

### ISSUE THREAD

**Issue by juarezasjunior** [juarezasjunior/KomberNet#7]
**Description**
When forgetting a password, the user should be able to reset it. An email to restore the password should be sent to him.

---
**Screenshots / Mockups**
NA.

---
**Acceptance Criteria**
- [ ] Page to reset the password;
- [ ] Email to restore the password;
- [ ] Page to add new password.

---
**Notes**
NA.

---
**Tasks**
NA.
